<?php

namespace Sylius\Bundle\MemberBundle\Repository;

/**
 * MemberExtendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberExtendRepository extends \Doctrine\ORM\EntityRepository
{
}
