<?php

namespace Sylius\Bundle\MemberBundle\Repository;

/**
 * MemberRecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberRecordRepository extends \Doctrine\ORM\EntityRepository
{
}
