member_extend_index:
    path:     /
    defaults: { _controller: "SyliusMemberBundle:MemberExtend:index" }
    methods:  GET

member_extend_show:
    path:     /{id}/show
    defaults: { _controller: "SyliusMemberBundle:MemberExtend:show" }
    methods:  GET



