sylius_admin_member_extend:
    resource: |
        alias: sylius.member_extend
        section: admin
        templates: SyliusAdminBundle:Crud
        except: ['show']
        redirect: index
        grid: sylius_admin_member_extend
        permission: true
        vars:
            all:
                subheader: sylius.ui.manage_member_extend
                templates:
                    form: SyliusAdminBundle:Member:_form_extend.html.twig
            index:
                icon: credit card alternative
    type: sylius.resource
