sylius_admin_member_record:
    resource: |
        alias: sylius.member_record
        section: admin
        templates: SyliusAdminBundle:Crud
        except: ['show']
        redirect: index
        grid: sylius_admin_member_record
        permission: true
        vars:
            all:
                subheader: sylius.ui.manage_member_record
                templates:
                    form: SyliusAdminBundle:Member:_form_record.html.twig
            index:
                icon: credit card alternative
    type: sylius.resource
