Sylius\Bundle\MemberBundle\Entity\MemberExtend:
    properties:
        money:
            - NotBlank:
                groups: [member]
        MemberCategory:
            - NotBlank:
                groups: [member]