Sylius\Bundle\MemberBundle\Entity\MemberCategory:
    properties:
        name:
            - NotBlank:
                groups: [member]
        gradeType:
            - NotBlank:
                message: 请设置会员等级所需积分
                groups: [member]