services:
    sylius.form.type.member_categroy:
        class: Sylius\Bundle\MemberBundle\Form\Type\MemberCategoryType
        arguments: [ %sylius.model.member_category.class%, ['sylius']]
        tags:
            - { name: form.type }
