sylius_shop_account_member_index:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.account_member:indexAction
        _sylius:
            section: shop_account
            template: "@SyliusShop/Account/Member/index.html.twig"
            paginate: false
            repository:
                method: findByCustomer
                arguments:
                    - "expr:service('sylius.context.customer').getCustomer()"