# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

jms_serializer:
    metadata:
        directories:
            sylius-payment:
                namespace_prefix: "Sylius\\Component\\Payment"
                path: "@SyliusPaymentBundle/Resources/config/serializer"

payum:
    gateways:
        unionpay:
            factory: omnipay_stripe
        alipay:
            factory: omnipay_alipay
        wechatpay:
            factory: omnipay_wechatpay